{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "symphony.automation.fullname" . }}
  labels: {{- include "symphony.automation.metaLabels" . | nindent 4 }}
  {{- with .Values.automation.deploymentAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.automation.updateStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.automation.replicas }}
  selector:
    matchLabels: {{- include "symphony.automation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "symphony.automation.podLabels" . | nindent 8 }}
      {{- with .Values.automation.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "symphony.automation.serviceAccountName" . }}
      {{- with .Values.automation.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.automation.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.automation.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.automation.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: automation
          image: {{ default (print .Values.global.image.registry "/automation") .Values.automation.image.repository }}:{{ default .Values.global.image.tag .Values.automation.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.automation.image.pullPolicy }}
          env:
            {{- with .Values.automation.spec.proxy.logger }}
            - name: LOGGER_HOST
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.automation.spec.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- /*
            This block should include `symphony.tracingEnv`, but the node jaeger client only supports
            Thrift when working with the agent.  This is a temporary hack until the node client supports
            grpc, at which point we can delete `agentThriftClient`.
            */ -}}
            {{- if and .Values.tracing.enabled .Values.tracing.jaeger.agentThriftEndpoint }}
            - name: TELEMETRY_TRACE_SAMPLING_PROBABILITY
              value: {{ int .Values.tracing.enabled | quote }}
            - name: TELEMETRY_TRACE_EXPORTER
              value: "jaeger"
            {{- with .Values.tracing.jaeger.agentThriftEndpoint }}
            - name: JAEGER_AGENT_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
          ports:
            {{- include "symphony.containerPorts" .Values.automation | nindent 12 }}
            - containerPort: {{ .Values.automation.service.internal.targetPort }}
              name: http-internal
          {{- $ = set .Values.automation.probes "path" "/api/flow/1.0/health" -}}
          {{- include "symphony.probes" .Values.automation | indent 10}}
          resources: {{- toYaml .Values.automation.resources | nindent 12 }}
