{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "symphony.scheduler.fullname" . }}
  labels: {{- include "symphony.scheduler.metaLabels" . | nindent 4 }}
  {{- with .Values.scheduler.deploymentAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.scheduler.updateStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels: {{- include "symphony.scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "symphony.scheduler.podLabels" . | nindent 8 }}
      {{- with .Values.scheduler.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "symphony.scheduler.serviceAccountName" . }}
      {{- with .Values.scheduler.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scheduler
          image: {{ default (print .Values.global.image.registry "/scheduler") .Values.scheduler.image.repository }}:{{ default .Values.global.image.tag .Values.scheduler.image.tag }}
          imagePullPolicy: {{ default .Values.global.image.pullPolicy .Values.scheduler.image.pullPolicy }}
          env:
            {{- with .Values.scheduler.spec.proxy.logger }}
            - name: LOGGER_HOST
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.scheduler.spec.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- /*
            This block should include `symphony.tracingEnv`, but the node jaeger client only supports
            Thrift when working with the agent.  This is a temporary hack until the node client supports
            grpc, at which point we can delete `agentThriftClient`.
            */ -}}
            {{- if and .Values.tracing.enabled .Values.tracing.jaeger.agentThriftEndpoint }}
            - name: TELEMETRY_TRACE_SAMPLING_PROBABILITY
              value: {{ int .Values.tracing.enabled | quote }}
            - name: TELEMETRY_TRACE_EXPORTER
              value: "jaeger"
            {{- with .Values.tracing.jaeger.agentThriftEndpoint }}
            - name: JAEGER_AGENT_ENDPOINT
              value: {{ . | quote }}
            {{- end }}
            {{- end }}
          ports:
            {{- include "symphony.containerPorts" .Values.scheduler | nindent 12 }}
            - containerPort: {{ .Values.scheduler.service.internal.targetPort }}
              name: http-internal
          {{- $ = set .Values.scheduler.probes "path" "/api/scheduler/1.0/health" -}}
          {{- include "symphony.probes" .Values.scheduler | indent 10}}
          resources: {{- toYaml .Values.scheduler.resources | nindent 12 }}
